import json
import jsonpath
import cx_Oracle
from jsonpath_ng import parse
# https://blog.csdn.net/nd211314555/article/details/88426529 jsonpath的基本操作

class get_message():
    def __init__(self,claim_no):
        self.claim_no = claim_no
    
    def get_message(self):
        conn = cx_Oracle.connect('apd_v50_test/apd_v50_test@192.168.200.25:1521/orcl')
        cursor = conn.cursor()
        result=cursor.execute(" select data from t_rule_audit_report_clm_model a where a.claim_id in (select b.claim_id from t_claim b where b.accident_no = '"+self.claim_no+"') order by a.modify_date desc" )
        data=cursor.fetchone()
        try:
            data = json.loads(str(data[0]))
            return data
        except :
            return None

class rule():
    def __init__(self,claim_no) -> None:
        self.claim_no = claim_no
        self.message = get_message(claim_no).get_message()
    
    # def get_data(self):
        self.accidentNo = jsonpath.jsonpath(self.message,expr='$.accLossInfo.accidentNo')
        self.reportDate = jsonpath.jsonpath(self.message,expr='$.claimWf.damageDateInReportNode')
        self.VIN = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.vin')
        self.plateNo = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.plateNo')
        self.brandModel = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.brandModel')
        self.engineNo = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.engineNo')
        self.vehicleSubModelName = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.vehicleSubModelName.currentSubmitValue')
        self.compulsoryVehicleVin = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryVehicleVin')
        self.commercialVehicleVin = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialVehicleVin')
        self.compulsoryVehiclePlateNo = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryVehiclePlateNo')
        self.commercialVehiclePlateNo = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialVehiclePlateNo')
        self.compulsoryVehicleSubModel = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryVehicleSubModel')
        self.compulsoryVehicleBrandModel = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryVehicleBrandModel')
        self.compulsoryVehicleEngineNo = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryVehicleEngineNo')
        self.commercialVehicleSubModel = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialVehicleSubModel')
        self.commercialVehicleBrandModel = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialVehicleBrandModel')
        self.commercialVehicleEngineNo = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialVehicleEngineNo')
        self.contactInfoList = jsonpath.jsonpath(self.message,expr='$.contactInfoList[*]')
        self.includeTypeList = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.includeTypeList')
        self.surveyFirstSiteFlag = jsonpath.jsonpath(self.message,expr='$.accLossInfo.surveyFirstSiteFlag')
        self.coverageCode = jsonpath.jsonpath(self.message,expr='$.coverageCode')
        self.accidentType = jsonpath.jsonpath(self.message,expr='$.accLossInfo.accidentType')
        self.versionType = jsonpath.jsonpath(self.message,expr='$.claimWf.versionType')
        self.damageReason = jsonpath.jsonpath(self.message,expr='$.accLossInfo.damageReason')
        self.vehicleMakeCode = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.vehicleMakeCode')
        self.vehicleSeriesCode = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.vehicleSeriesCode')
        self.vehicleHash_current = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.vehicleHash.currentSubmitValue')
        self.vehicleHash_lastSubmitValue = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.vehicleHash.lastSubmitValue')
        self.commercialCoverageList = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialCoverageList[*].coverageCode')
        self.compulsoryCoverageList = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryCoverageList[*].coverageCode')    
        self.totalEstimateAmount = jsonpath.jsonpath(self.message,expr='$.feeInfo.totalEstimateAmount.currentSubmitValue')
        self.damageDate = jsonpath.jsonpath(self.message,expr='$.claimWf.damageDate')
        self.lossVehicleType = jsonpath.jsonpath(self.message,expr='$.vehicleInfo.lossVehicleType')
        self.compulsoryPolicyStartDate = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryPolicyStartDate')  
        self.commercialPolicyStartDate = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialPolicyStartDate') 
        self.compulsoryRenewPolicyFlag = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryRenewPolicyFlag') 
        self.commercialRenewPolicyFlag = jsonpath.jsonpath(self.message,expr='$.policyInfo.commercialRenewPolicyFlag')
        self.compulsoryPolicyEndDate = jsonpath.jsonpath(self.message,expr='$.policyInfo.compulsoryPolicyEndDate')
        self.commercialPolicyEndDate = jsonpath.jsonpath(self.message,expr= '$.policyInfo.commercialPolicyEndDate')
        self.standardPartId = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].standardPartId')
        self.partName = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partName')
        self.partId = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partId')
        self.quantity_current = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].quantity.currentSubmitValue')
        self.quantity_lastSubmitValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].quantity.lastSubmitValue')
        self.manualFlag = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].manualFlag')
        self.manualMatchedUniquePart_standardid = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].manualMatchedUniquePart.standardPartId')
        self.manualMatchedUniquePart_partName = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].manualMatchedUniquePart.partName')
        self.operationType = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].operationType.currentSubmitValue')
        self.claimEstimateItemId = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].claimEstimateItemId')
        self.partFeeDiscount = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partFeeDiscount.currentSubmitValue')
        self.repairFeeDiscount = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].repairFeeDiscount.currentSubmitValue')
        self.paintFeeDiscount = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].paintFeeDiscount.currentSubmitValue')
        self.allPaintFeeSum = jsonpath.jsonpath(self.message,expr='$.feeInfo.allPaintFeeSum.currentSubmitValue')
        self.removeFeeDiscount = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].removeFeeDiscount.currentSubmitValue')
        self.allRemoveFeeSum = jsonpath.jsonpath(self.message,expr='$.feeInfo.allRemoveFeeSum.currentSubmitValue')
        self.wholePaintFLag = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].wholePaintFLag')
        self.outerFlag_source = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.outerFlag.valueSource')
        self.outerFlag_instantValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.outerFlag.instantValue')
        self.outerFlag_standardValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.outerFlag.standardValue')
        self.outerFlag_seriesValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.outerFlag.seriesValue')
        self.materialCode = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].materialCode')
        self.materialName = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].materialName')
        self.materialTotalAmount = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].materialTotalAmount.currentSubmitValue')
        self.assemblyPartRelFlag = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.assemblyPartRelFlag.valueSource')
        self.assemblyPartIds_valueSource = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.assemblyPartIds.valueSource')
        self.assemblyPartIds_instantValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.assemblyPartIds.instantValue')
        self.assemblyPartIds_standardValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.assemblyPartIds.standardValue')
        self.claimMaterialList_claimEstimateItemId = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].claimEstimateItemId')
        self.claimMaterialList_materialCode = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].materialCode')
        self.claimMaterialList_materialName = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].materialName')
        self.claimMaterialList_manualFlag = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].manualFlag')
        self.manualMatchedMaterial_materialCode = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].manualMatchedMaterial.materialCode')
        self.manualMatchedMaterial_materialName = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].manualMatchedMaterial.materialName')
        self.claimMaterialList_materialTotalAmount = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimMaterialList[*].materialTotalAmount.currentSubmitValue')
        self.glassFlag_valueSource = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.glassFlag.valueSource')
        self.glassFlag_instantValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.glassFlag.instantValue')
        self.glassFlag_standardValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.glassFlag.standardValue')
        self.glassFlag_seriesValue = jsonpath.jsonpath(self.message,expr='$.lossInfo.claimPartList[*].partAttribInfo.glassFlag.seriesValue')

    def rule_0101010005(self):
        print(self.coverageCode)
        print(self.commercialCoverageList,self.compulsoryCoverageList)
        print(self.damageReason)
        print(self.vehicleMakeCode)
        print(self.partName)
        print(self.standardPartId)
        print(self.manualFlag)
        print(self.manualMatchedUniquePart_standardid)
        print(self.manualMatchedUniquePart_partName)
        print(self.operationType)
        print(self.partFeeDiscount)
        print(self.repairFeeDiscount)
        print(self.removeFeeDiscount)
        print(self.paintFeeDiscount)

    def rule_0101010006(self):
        print(self.versionType)
        print(self.commercialCoverageList,self.compulsoryCoverageList)
        print(self.lossVehicleType)
        print(self.accidentType)
        print(self.allPaintFeeSum)
        print(self.allRemoveFeeSum)
        print(self.claimEstimateItemId)
        print(self.operationType)
        print(self.paintFeeDiscount)
        print(self.wholePaintFLag)
        print(self.outerFlag_source)
        print(self.outerFlag_instantValue)
        print(self.outerFlag_standardValue)
        print(self.outerFlag_seriesValue)

    def rule_0101010007(self):
        print(self.commercialCoverageList,self.compulsoryCoverageList)
        print(self.lossVehicleType)
        print(self.damageReason)

    def rule_0101010008(self):
        print(self.lossVehicleType)
        print(self.commercialCoverageList,self.compulsoryCoverageList)
        print(self.damageReason)
        print(self.partName)
        print(self.standardPartId)
        print(self.manualFlag)
        print(self.manualMatchedUniquePart_standardid)
        print(self.manualMatchedUniquePart_partName)
        print(self.operationType)
        print(self.partFeeDiscount)
        print(self.repairFeeDiscount)
        print(self.removeFeeDiscount)
        print(self.paintFeeDiscount) 

    def rule_0101010010(self):
        print(self.versionType)
        print(self.commercialCoverageList,self.compulsoryCoverageList)
        print(self.lossVehicleType)
        print(self.claimEstimateItemId)
        print(self.partName)
        print(self.standardPartId)
        print(self.manualFlag)
        print(self.manualMatchedUniquePart_standardid)
        print(self.manualMatchedUniquePart_partName)
        print(self.operationType)
        print(self.partFeeDiscount)
        print(self.repairFeeDiscount)
        print(self.removeFeeDiscount)
        print(self.paintFeeDiscount)     
        print(self.materialCode)
        print(self.materialName)
        print(self.materialTotalAmount)    
   
    def rule_0104010003(self):
        print(1,self.versionType)
        print(2,self.vehicleMakeCode)
        print(3,self.vehicleSeriesCode)    
        print(4,self.partFeeDiscount)
        print(5,self.repairFeeDiscount)
        print(6,self.removeFeeDiscount)
        print(7,self.paintFeeDiscount)   
        print(8,self.claimEstimateItemId)
        print(9,self.partName)
        print(10,self.partId)
        print(11,self.standardPartId)
        print(12,self.assemblyPartRelFlag)
        print(13,self.assemblyPartIds_valueSource)
        print(14,self.assemblyPartIds_instantValue)
        print(15,self.assemblyPartIds_standardValue)

    def rule_0107010040(self):
        print(1,self.vehicleHash_current)
        print(2,self.vehicleHash_lastSubmitValue)
        print(3,self.partName)
        print(4,self.quantity_current)
        print(5,self.quantity_lastSubmitValue)
    
    def rule_0101010001(self):
        print(self.surveyFirstSiteFlag)
    
    def rule_0101010002(self):
        print(1,self.versionType)
        print(2,self.coverageCode)
        print(3,self.lossVehicleType)
        print(4,self.claimMaterialList_claimEstimateItemId)
        print(5,self.claimMaterialList_materialCode)
        print(6,self.claimMaterialList_materialName)
        print(7,self.claimMaterialList_manualFlag)
        print(8,self.manualMatchedMaterial_materialCode)
        print(9,self.manualMatchedMaterial_materialName)
        print(10,self.claimMaterialList_materialTotalAmount)
        print(11,self.claimEstimateItemId)
        print(12,self.partName)
        print(13,self.standardPartId)
        print(14,self.manualFlag)
        print(15,self.manualMatchedUniquePart_partName)
        print(16,self.manualMatchedUniquePart_standardid)
        print(17,self.operationType)
        print(18,self.partFeeDiscount)
        print(19,self.repairFeeDiscount)
        print(20,self.glassFlag_valueSource)
        print(21,self.glassFlag_instantValue)
        print(22,self.glassFlag_standardValue)
        print(23,self.glassFlag_seriesValue)
    
    def rule_0101010011(self):
        print(self.coverageCode)
        print(self.damageReason)
        print(self.totalEstimateAmount)
        print(self.partName)
        print(self.manualMatchedUniquePart_partName)
        print(self.manualFlag)
        print(self.operationType)
        print(self.partFeeDiscount)
        print(self.repairFeeDiscount)
        print(self.removeFeeDiscount)
        print(self.paintFeeDiscount)

    def rule_0101010013(self):
        print(self.contactInfoList)
        print(self.vehicleMakeCode)
        print(self.includeTypeList)
        print(self.totalEstimateAmount)
    
    def rule_0101010016(self):
        print(self.commercialPolicyStartDate)
        print(self.compulsoryPolicyStartDate)
        print(self.commercialRenewPolicyFlag)
        print(self.compulsoryRenewPolicyFlag)
        print(self.damageDate)
        print(12,self.partName)
        print(13,self.standardPartId)
        print(14,self.manualFlag)
        print(15,self.manualMatchedUniquePart_partName)
        print(16,self.manualMatchedUniquePart_standardid)
        print(17,self.operationType)
        print(18,self.partFeeDiscount)
    
    def rule_0101010017(self):
        print(1,self.totalEstimateAmount)
        print(2,self.damageDate)
        print(3,self.lossVehicleType)
        print(4,self.commercialRenewPolicyFlag)
        print(5,self.compulsoryRenewPolicyFlag)
        print(6,self.commercialPolicyStartDate)
        print(7,self.compulsoryPolicyStartDate)
        print(8,self.operationType)
        print(9,self.partFeeDiscount)
        print(10,self.repairFeeDiscount)
        print(11,self.paintFeeDiscount)
        print(12,self.removeFeeDiscount)
        print(13,self.standardPartId)
        print(14,self.partName)
        print(15,self.manualFlag)
        print(16,self.manualMatchedUniquePart_standardid)
        print(17,self.manualMatchedUniquePart_partName)
    
    def rule_0101010019(self):
        print(self.reportDate)
        print(self.damageDate)
    
    def rule_0101010020(self):
        print(1,self.versionType)
        print(2,self.lossVehicleType)
        print(3,self.totalEstimateAmount)
        print(4,self.brandModel)
        print(5,self.engineNo)
        print(6,self.vehicleSubModelName)
        print(7,self.compulsoryVehicleSubModel)
        print(8,self.compulsoryVehicleBrandModel)
        print(9,self.compulsoryVehicleEngineNo)
        print(10,self.commercialVehicleSubModel)
        print(11,self.commercialVehicleBrandModel)
        print(12,self.commercialVehicleEngineNo)
    
    def rule_0101010021(self):
        print(self.VIN)
        print(self.commercialVehicleVin)
        print(self.compulsoryVehicleVin)
        print(self.lossVehicleType)
        print(self.totalEstimateAmount)
    
    def rule_0101010022(self):
        print(self.plateNo)
        print(self.commercialVehiclePlateNo)
        print(self.compulsoryVehiclePlateNo)
        print(self.lossVehicleType)
        print(self.totalEstimateAmount)
    
    def rule_0102010001(self):
        print(self.VIN)
        print(self.plateNo)
        print(self.damageDate)
        print(self.lossVehicleType)
        print(self.accidentNo)
    
    def rule_0102010002(self):
        print(self.VIN)
        print(self.plateNo)
        print(self.damageDate)
        print(self.totalEstimateAmount)
        print(self.lossVehicleType)
        print(self.accidentNo)
        print(self.versionType)

if __name__ == '__main__':
    claim_no = 'acc_20210406_001'
    rule_0101010005 = rule(claim_no).rule_0102010001()